### PR TITLE
fix:Table spinner not stop after api call

### LINKED ISSUE #606: Home: Table spinner not stop after api call
I want to work on this issue

### PR DESCRIPTION
**Pull request by VAIBHAVSING**
fixes #606 
image

### CODE REVIEW

**Comment by VAIBHAVSING** [comment]
@heliocastro , sorry for accidentally closing the PR. I accidentally deleted the branch.

File: src/app/[locale]/home/components/MyComponentsWidget.tsx [hunk 1]
```diff
@@ -67,14 +66,15 @@ function MyComponentsWidget(): ReactNode {
...
-                    setLoading(false)
                 } else {
                     setData([])
-                    setLoading(false)
                 }
             })
-            .catch(() => {
-                console.error('False to fetch components')
+            .catch((err:Error) => {
+                console.error('Error:',err)
```
Comment (heliocastro) [inline src/app/[locale]/home/components/MyComponentsWidget.tsx:74]: No console output
Add proper error handling

File: src/app/[locale]/home/components/MyProjectsWidget.tsx [hunk 2]
```diff
@@ -71,11 +70,13 @@ function MyProjectsWidget(): ReactNode {
                             item.version ?? '',
                         ]),
                     )
-                    setLoading(false)
                 }
             })
-            .catch(() => {
-                console.error('False to fetch components')
+            .catch((err:Error) => {
+                console.error('Error',err)
```
Comment (heliocastro) [inline src/app/[locale]/home/components/MyProjectsWidget.tsx:76]: No console output
Add proper error handling

File: src/app/[locale]/home/components/MySubscriptionsWidget.tsx [hunk 3]
```diff
@@ -71,13 +71,17 @@ function MySubscriptionsWidget(): ReactNode {
                     setReleaseData([])
                 }
             })
-            .catch((err) => console.error(err))
-        setLoading(false)
-    }, [fetchData,reload])
+            .catch((err: Error) => {
+                console.error('Error',err)
```
Comment (heliocastro) [inline src/app/[locale]/home/components/MySubscriptionsWidget.tsx:75]: No console output
Add proper error handling

File: src/app/[locale]/home/components/MyTaskAssignmentsWidget.tsx [hunk 4]
```diff
@@ -68,10 +67,15 @@ function MyTaskAssignmentsWidget(): ReactNode {
                             taskAssignmentStatus[item.moderationState ?? 'INPROGRESS'],
                         ]),
                     )
-                    setLoading(false)
                 }
             },
         )
+        .catch((err:Error) => {
+            console.error('Error',err)
```
Comment (heliocastro) [inline src/app/[locale]/home/components/MyTaskAssignmentsWidget.tsx:74]: No console output
Add proper error handling

File: src/app/[locale]/home/components/MyTaskSubmissionsWidget.tsx [hunk 5]
```diff
@@ -71,10 +70,15 @@ function MyTaskSubmissionsWidget(): ReactNode {
                             item.id,
                         ]),
                     )
-                    setLoading(false)
                 }
             },
         )
+        .catch((err: Error) => {
+            console.error('Error', err)
```
Comment (heliocastro) [inline src/app/[locale]/home/components/MyTaskSubmissionsWidget.tsx:77]: No console output
Add proper error handling

File: src/app/[locale]/home/components/RecentComponentsWidget.tsx [hunk 6]
```diff
@@ -66,11 +65,16 @@ function RecentComponentsWidget(): ReactNode {
                         </li>,
                     ]),
                 )
-                setLoading(false)
             } else {
                 setRecentComponent([])
             }
         })
+        .catch((err:Error)=>{
+            console.error('Error',err)
```
Comment (heliocastro) [inline src/app/[locale]/home/components/RecentComponentsWidget.tsx:73]: No console output
Add proper error handling

File: src/app/[locale]/home/components/RecentReleasesWidget.tsx [hunk 7]
```diff
@@ -68,12 +67,16 @@ function RecentReleasesWidget() : ReactNode {
...
                     ]),
                 )
-                setLoading(false)
             } else {
                 setRecentRelease([])
-                setLoading(false)
             }
         })
+        .catch((err:Error)=>{
+            console.error('Error',err)
```
Comment (heliocastro) [inline src/app/[locale]/home/components/RecentReleasesWidget.tsx:75]: No console output
Add proper error handling

**Review by heliocastro — CHANGES_REQUESTED** [review]
Provide better error handling

**Comment by VAIBHAVSING** [comment]
@heliocastro  sorry for being late can i display alert to users

**Comment by heliocastro** [comment]
> @heliocastro sorry for being late can i display alert to users . sol2: can i implement if api fails and call again after 10 second if this sol not good please suggest me solution

None of then:

https://nextjs.org/docs/pages/building-your-application/configuring/error-handling

**Comment by VAIBHAVSING** [comment]
@heliocastro why this give lint error

**Comment by heliocastro** [comment]
> @heliocastro why this give lint error

The PR title, ( not commits ) not accepts () in the name because automate type.
I fixed this one and review it

**Comment by heliocastro** [comment]
@VAIBHAVSING You have strange merge commits in the middle of your tree, you need fix it

**Comment by VAIBHAVSING** [comment]
@heliocastro 
ERROR the following files don't have a valid license header: 
src/app/[locale]/home/error.tsx 
ERROR one or more files does not have a valid license header 
Error: Process completed with exit code 1. 
what does this error mean ??
It's like to add some license header at error.tsx
https://github.com/eclipse-sw360/sw360-frontend/blob/1b87469c92f7b15662e3a1b8f671a38d23fbca33/src/app/%5Blocale%5D/page.tsx#L1C1-L9C29

**Comment by VAIBHAVSING** [comment]
[> @heliocastro ERROR the following files don't have a valid license header: src/app/[locale]/home/error.tsx ERROR one or more files does not have a valid license header Error: Process completed with exit code 1. what does this error mean ?? It's like to add some license header at error.tsx
> 
> * 

](https://github.com/eclipse-sw360/sw360-frontend/blob/1b87469c92f7b15662e3a1b8f671a38d23fbca33/src/app/%5Blocale%5D/page.tsx#L1C1-L9C29)

**Comment by VAIBHAVSING** [comment]
Error look like this in home page
Screenshot from 2025-03-22 23-08-22

**Comment by VAIBHAVSING** [comment]
@heliocastro  its due to i added error.tsx file what header need to be added ?

File: src/app/[locale]/home/error.tsx [hunk 8]
```diff
@@ -0,0 +1,94 @@
...
+  error,
+  reset,
+}: {
+  error: Error & { digest?: string }
+  reset: () => void
+}) {
+  const [isVisible, setIsVisible] = useState(true)
+  
+  useEffect(() => {
+    console.log("Error caught:", error)
```
Comment (heliocastro) [inline src/app/[locale]/home/error.tsx:25]: Console log

**Review by heliocastro — CHANGES_REQUESTED** [review]
Another console log pending

File: src/app/[locale]/home/error.tsx (hunk 8 above)
Comment (VAIBHAVSING) [reply src/app/[locale]/home/error.tsx]: hello @heliocastro 
can you review it

**Review by heliocastro — DISMISSED** [review]
Good to go
