### PR TITLE
Fix: Project Relationship not shown on Duplicate Project page, fixes #1358

### LINKED ISSUE #1358: Project Relationship Missing
In the "Linked Releases and Projects" tab of the Project Details Page, we have a Linked Projects Table which has a column "Project Relationship". On opening the "Duplicate Project" page(click on the duplicate icon in the Actions column of the projects table in the projects tab), this column is not taking up the value returned by the api. It always takes up the default unknown value.

### PR DESCRIPTION
**Pull request by Anushreebasics**
fixes #1358

The backend already provides the correct relationship information in project.linkedProjects.
However, the Duplicate Project page was incorrectly reading the relationship from the linked project object itself, causing the UI to always default to UNKNOWN.

This fix ensures the relationship is correctly mapped from the parent project’s linkedProjects metadata.

@heliocastro @GMishx please review this PR

### CODE REVIEW

**Review by heliocastro — APPROVED** [review]
Good to go. Some remarks from copilot is valid to solve in the future

**Comment by Anushreebasics** [comment]
@heliocastro please review the changes

File: src/app/[locale]/components/detail/[id]/components/ComponentGeneral.tsx [hunk 1]
```diff
@@ -111,6 +111,14 @@ const ComponentGeneral = ({ component, componentId }: Props): ReactNode => {
                         <span className='sw360-tt'>{component.componentType}</span>
                     </td>
                 </tr>
+                <tr>
+                    <td>{t('CycloneDX Component Type')}:</td>
```
Comment (deo002) [inline src/app/[locale]/components/detail/[id]/components/ComponentGeneral.tsx]: Please add translations for all strings you add. If you are using VS Code, we use an extension called i18ally.

File: src/app/[locale]/components/detail/[id]/components/ComponentGeneral.tsx [hunk 2]
```diff
@@ -132,6 +140,23 @@ const ComponentGeneral = ({ component, componentId }: Props): ReactNode => {
                         )}
                     </td>
                 </tr>
+                <tr>
+                    <td>{t('VCS / Repository URL')}:</td>
```
Comment (deo002) [inline src/app/[locale]/components/detail/[id]/components/ComponentGeneral.tsx]: Here as well
