### PR TITLE
fix: Add Alert for processing state 

### LINKED ISSUE #1359: 'Processing' Alert Box Missing in Project Linked Releases Modal
## Description
Processing Alert Box is missing in the Project Linked Releases Modal.

### PR DESCRIPTION
**Pull request by manhuu14**
Description:

Added a showProcessing alert in LinkedReleasesModal while fetching release data to improve UX.

Fixed missing Alert import from react-bootstrap.

Ensured modal resets and project payload updates correctly after linking releases. 

Fixes #1359

### CODE REVIEW

File: src/components/sw360/LinkedReleasesModal/LinkedReleasesModal.tsx [hunk 1]
```diff
@@ -323,6 +324,16 @@ export default function LinkedReleasesModal({ projectPayload, setProjectPayload,
                 <Modal.Title id='linked-projects-modal'>{t('Link Releases')}</Modal.Title>
             </Modal.Header>
             <Modal.Body>
+                {showProcessing && (
```
Comment (deo002) [inline src/components/sw360/LinkedReleasesModal/LinkedReleasesModal.tsx]: This is not needed,  we already have a processing alert in the table code

**Review by heliocastro — APPROVED** [review]
Good to go
