### PR TITLE
fix:Apply Filter at All Table in Home

### LINKED ISSUE #528: Filter at My Project table

### PR DESCRIPTION
**Pull request by VAIBHAVSING**
fixes #528 
Sorting is working fine in Jsx Element coloumn as well as normal coloumn

### CODE REVIEW

File: src/app/[locale]/home/components/MyComponentsWidget.tsx [hunk 1]
```diff
@@ -80,15 +80,26 @@ function MyComponentsWidget(): ReactNode {
...
+        name: t('Component Name'),
+        formatter: (cell: string) => {
+            const [name, id] = cell.split('|')
+            return _(
+                <Link href={'components/detail/' + id}>{name}</Link>,
+            )
+        },
+    }, t('Description'),
+    ]
+    // const columns = [t('Component Name'), t('Description')]
```
Comment (hoangnt2) [inline src/app/[locale]/home/components/MyComponentsWidget.tsx:97]: remove commented code

Comment (VAIBHAVSING) [reply src/app/[locale]/home/components/MyComponentsWidget.tsx]: @hoangnt2  @heliocastro
hello, I removed comment please can you review it

**Review by heliocastro — APPROVED** [review]
Good to go
